name: Package

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  package:
    uses: normlanguage/registry/.github/workflows/package.yml@2bb70658e6c5cb774a53388183ce43f4d0292c15
    with:
      norm-version: 0.20.0
